highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
url: "https://colmont.github.io"
title: "Colin Doumont"
description: "PhD student at TÃ¼bingen AI Center"
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-katex
katex:
  js_path: "assets"
  rendering_options:
    throw_error: false
    error_color: "#cc0000"